# Generated by Django 3.0.7 on 2020-06-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created',
        ),
    ]
